version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: 2.1.4
          command: bundle -v
      - ruby/bundle-install